-- +goose Up
ALTER TABLE player ADD COLUMN ship_attack INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN ship_defense INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN ship_hull INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN ship_max_hull INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN trips INTEGER NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE player DROP COLUMN ship_attack;
ALTER TABLE player DROP COLUMN ship_defense;
ALTER TABLE player DROP COLUMN ship_hull;
ALTER TABLE player DROP COLUMN ship_max_hull;
ALTER TABLE player DROP COLUMN trips;
